### ISSUE TITLE
[FEATURE REQUEST] Support Enbridge's Green Button Implementation

### ISSUE THREAD

**Issue by dangowans** [cityssm/EMILE#16]
**What feature are you suggesting?**

Support for Enbridge's upcoming [Green Button Connect My Data Implementation](https://www.enbridgegas.com/download-and-share-your-data).

**Is your feature request related to a problem?**

No.

**Are there any workarounds?  Are there any alternative solutions that would work?**

Download the data manually for 30+ assets using Green Button Download My Data, and upload it into EMILE. Note that manually generated Green Button files from Enbridge are importing successfully, so [node-green-button-parser](https://github.com/cityssm/node-green-button-parser) should be ready.

**Are there any other helpful details?**

- [Enbridge's Third Party Application](https://www.enbridgegas.com/download-and-share-your-data/third-parties) is not yet ready.

- The requirements to become a third party are more extensive than PUC, based on [Enbridge's FAQ page](https://www.enbridgegas.com/download-and-share-your-data/third-party-frequently-asked-questions).

- The bulk download endpoint appears more complicated compared to PUC. Rather than providing the data on request like PUC, Enbridge's solution requires a public facing notify URL to notify when data is ready to download over SFTP. Updates to [node-green-button-subscriber](https://github.com/cityssm/node-green-button-subscriber) will be required.

**Comment by dangowans** [comment]
**From the [FAQ](https://www.enbridgegas.com/download-and-share-your-data/third-party-frequently-asked-questions)**

> **Are you supporting Representational State Transfer (REST) or SFTP for bulk data request?**
> 
> We support REST for bulk data requests. When you access our bulk API, you’ll receive a 202 response immediately if the request was sent with the correct token. We’ll process your request in a batch mode and send you the Batchlist via the Notify URI. You’ll have to use the URIs from the Batchlist to get the data, use Client_Access_Token when you access the URIs. Please note that – our backend system allows bulk data sharing between 7 am – 4 pm ET only. If you request the Batchlist URIs outside of this window, your request will be refused.

**TODOs**

- [ ] 🧱 Handle accepting 202 responses in [node-green-button-subscriber](https://github.com/cityssm/node-green-button-subscriber).
- [ ] 👂 Create a notify URL to handle notifications when the data is ready to download.
- [ ] 🕛 Implement time-of-day limits to only make requests between 7am and 4pm. Handle the time-of-day rejections.

**Comment by dangowans** [comment]
Enbridge's third party application process is now available.
